### PR TITLE
Pull in upstream updates and add test user

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description

This pull request pulls in upstream updates from [cisagov/skeleton-ansible-role](https://github.com/cisagov/skeleton-ansible-role) and adds a test user so that this Ansible role can be properly tested in GitHub Actions.

## 💭 Motivation and Context

A test user is required because this role must be able to obtain the Cobalt Strike tarball and license file from our private bucket in order to perform its function.

## 🧪 Testing

All pre-commit hooks and molecule tests pass.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by dav3r — COMMENTED** [review]
This all looks solid to me- nice work! 👍 

The one question I have before I approve is: how are we going to build our Production TeamServers for the PCA team?  The [`pca-teamserver-aws`](https://github.com/cisagov/pca-teamserver-aws) uses this Ansible role to install Cobalt Strike, so I believe we need to either:
- Ensure that the current (non-COOL) CyHy account can access the Cobalt Strike objects in `cisa-cool-third-party-production` (this is probably the simplest solution)
- Update [`pca-teamserver-aws`](https://github.com/cisagov/pca-teamserver-aws) to build and deploy in the COOL (we will need this eventually, but not sure if we need to do it now)

**Comment by jsf9k** [comment]
> The one question I have before I approve is: how are we going to build our Production TeamServers for the PCA team?

@dav3r - you are correct.  This is something I forgot to do.  It is handled in commits ac6a032 and cisagov/pca-teamserver-aws@fabd003c1bf9be840e1fa82f561cc31d5f604a3c.  (I will be creating a pull request from that branch soon.)

This will allow the old PCA teamserver stuff to continue pottering around in the old CyHy account for now.

**Review by dav3r — APPROVED** [review]
Excellent- that works for me! 🚀 

I will take some of this sauce and apply it to [`ansible-role-nessus`](https://github.com/cisagov/ansible-role-nessus) so that it supports multi-account setups and ensure that it continues to work with our Production CyHy images.

**Review by felddy — APPROVED** [review]
Looks good.  Nice PCA support there man!  🐟

**Comment by dav3r** [comment]
One difference that I just noticed between the IAM role that you create for the test user in this repo vs. the test user in `ansible-role-nessus` is that you don't restrict the [`ThirdPartyBucketRead-test-ansible-role-cobalt-strike` role](https://github.com/cisagov/ansible-role-cobalt-strike/blob/improvement/upstream-updates/terraform/iam_user.tf#L14-L33) to only be used by the test user like we currently do with the [`ThirdPartyBucketRead-test-ansible-role-nessus` role](https://github.com/cisagov/ansible-role-nessus/blob/develop/terraform/iam_user.tf#L28).

If you add the test user's name to the list of `iam_usernames` when calling [`s3-read-role-tf-module`](https://github.com/cisagov/s3-read-role-tf-module), only that user can assume the role.  Otherwise, any user in the account may be allowed to assume the role.

Let me know which way you want to go with this- we should be doing this similarly across all of our Ansible roles.

**Comment by jsf9k** [comment]
> If you add the test user's name to the list of `iam_usernames` when calling [`s3-read-role-tf-module`](https://github.com/cisagov/s3-read-role-tf-module), only that user can assume the role. Otherwise, any user in the account may be allowed to assume the role.

I wanted my personal IAM user to be able to assume the role, so that I could run `AWS_PROFILE=cool-images-test-ansible-role-cobalt-strike molecule test` from my local machine.  

To be clear, the users in the delegated account are only allowed to assume the role if there is an explicit policy in the delegated account allowing them to do so (which I added).  By default they are not allowed to assume the role.

**Comment by dav3r** [comment]
Understood- I wanted to be sure that you meant to do it that way.  I will update the test user role for [`ansible-role-nessus`](https://github.com/cisagov/ansible-role-nessus) to be similar.

**Pull request merged**
